// UjuziAI Module Configuration
// 7 Tracks with real Google resources

export const TRACKS = [
  {
    id: 'ai',
    name: 'Intelligence Artificielle',
    shortName: 'IA',
    description: 'Maitrisez les fondamentaux de IA les agents intelligents et les API Gemini',
    color: 'blue',
    gradient: 'from-blue-500 to-indigo-600',
    bgLight: 'bg-blue-500/10',
    bgDark: 'bg-blue-500/15',
    borderColor: 'border-blue-500/30',
    textColor: 'text-blue-500 dark:text-blue-400',
    badgeClass: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30',
    icon: 'brain',
    logo: '/gemini-logo-icon.jpg',
    order: 1,
  },
  {
    id: 'flutter',
    name: 'Flutter & Dart',
    shortName: 'Flutter',
    description: 'Creez des applications mobiles multiplateformes avec Flutter et Firebase',
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-500',
    bgLight: 'bg-cyan-500/10',
    bgDark: 'bg-cyan-500/15',
    borderColor: 'border-cyan-500/30',
    textColor: 'text-cyan-500 dark:text-cyan-400',
    badgeClass: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    icon: 'smartphone',
    logo: '/flutter-logo-icon.png',
    order: 2,
  },
  {
    id: 'web',
    name: 'Developpement Web',
    shortName: 'Web',
    description: 'Construisez des applications web modernes avec IA cote client et les extensions Chrome',
    color: 'green',
    gradient: 'from-green-500 to-emerald-600',
    bgLight: 'bg-green-500/10',
    bgDark: 'bg-green-500/15',
    borderColor: 'border-green-500/30',
    textColor: 'text-green-500 dark:text-green-400',
    badgeClass: 'bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/30',
    icon: 'globe',
    logo: '/chrome-logo-icon.png',
    order: 3,
  },
  {
    id: 'cloud',
    name: 'Google Cloud',
    shortName: 'Cloud',
    description: 'Maitrisez les services Google Cloud Platform IA agentique et le DevOps',
    color: 'sky',
    gradient: 'from-sky-500 to-blue-600',
    bgLight: 'bg-sky-500/10',
    bgDark: 'bg-sky-500/15',
    borderColor: 'border-sky-500/30',
    textColor: 'text-sky-500 dark:text-sky-400',
    badgeClass: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30',
    icon: 'cloud',
    logo: '/google-cloud-logo-icon.jpg',
    order: 4,
  },
  {
    id: 'angular',
    name: 'Angular',
    shortName: 'Angular',
    description: 'Developpez des applications avec Angular Vertex AI et Genkit',
    color: 'red',
    gradient: 'from-red-500 to-rose-600',
    bgLight: 'bg-red-500/10',
    bgDark: 'bg-red-500/15',
    borderColor: 'border-red-500/30',
    textColor: 'text-red-500 dark:text-red-400',
    badgeClass: 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30',
    icon: 'hexagon',
    logo: '/angular-logo-icon.jpg',
    order: 5,
  },
  {
    id: 'kotlin',
    name: 'Kotlin & Android',
    shortName: 'Kotlin',
    description: 'Creez des applications Android natives avec Kotlin LiteRT et ML Kit',
    color: 'purple',
    gradient: 'from-purple-500 to-violet-600',
    bgLight: 'bg-purple-500/10',
    bgDark: 'bg-purple-500/15',
    borderColor: 'border-purple-500/30',
    textColor: 'text-purple-500 dark:text-purple-400',
    badgeClass: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/30',
    icon: 'code',
    logo: '/kotlin-logo-icon.jpg',
    order: 6,
  },
  {
    id: 'skills',
    name: 'Google Skills',
    shortName: 'Skills',
    description: 'Parcours de certification Google Skills Labs Gemini et Machine Learning',
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    bgLight: 'bg-emerald-500/10',
    bgDark: 'bg-emerald-500/15',
    borderColor: 'border-emerald-500/30',
    textColor: 'text-emerald-500 dark:text-emerald-400',
    badgeClass: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    icon: 'sparkles',
    logo: '/google-skills-logo-icon.png',
    order: 7,
  },
];

export const MODULES = [
  // ---- TRACK: IA (16 modules) ----
  {
    id: 'ai-antigravity-start',
    title: 'Premiers pas avec Google Antigravity',
    description: 'Antigravity fournit un centre de controle pour gerer les agents autonomes qui peuvent planifier coder et naviguer sur le Web.',
    codelabUrl: 'https://goo.gle/start-with-antigravity',
    iconName: 'rocket',
    trackId: 'ai',
    order: 1,
    estimatedTime: '60 min',
    difficulty: 'Debutant',
    topics: ['Antigravity', 'Agents IA', 'Codage assiste'],
  },
  {
    id: 'ai-antigravity-build',
    title: 'Compiler avec Google Antigravity',
    description: 'Utilisez Antigravity pour creer des applications reelles full stack et des tests unitaires de niveau entreprise.',
    codelabUrl: 'https://goo.gle/building-with-google-antigravity',
    iconName: 'bot',
    trackId: 'ai',
    order: 2,
    estimatedTime: '75 min',
    difficulty: 'Intermediaire',
    topics: ['Antigravity', 'Full Stack', 'Tests unitaires'],
  },
  {
    id: 'ai-antigravity-deploy',
    title: 'Compiler et deployer sur Google Cloud avec Antigravity',
    description: 'Utilisez Google Antigravity pour concevoir creer et deployer une application sans serveur sur Google Cloud avec Cloud Run et Gemini.',
    codelabUrl: 'https://goo.gle/building-and-deploy-with-antigravity',
    iconName: 'cloud',
    trackId: 'ai',
    order: 3,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['Antigravity', 'Cloud Run', 'BigQuery', 'Serverless'],
  },
  {
    id: 'ai-gemini-cli-security',
    title: 'Revue de code et securite avec Gemini CLI',
    description: 'Utilisez la Gemini CLI et ses extensions pour examiner le code et analyser la securite dans votre workflow de developpement.',
    codelabUrl: 'https://goo.gle/code-review-security-analysis-gemini-cli',
    iconName: 'shield-check',
    trackId: 'ai',
    order: 4,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['Gemini CLI', 'Securite', 'Revue de code', 'Extensions'],
  },
  {
    id: 'ai-gemini-developers',
    title: 'Gemini pour les developpeurs',
    description: 'Decouvrez les modeles Gemini : reflexion approfondie ancrage recherche Google comprehension spatiale API Live sortie audio et image native.',
    codelabUrl: 'https://goo.gle/gemini-for-developers',
    iconName: 'sparkles',
    trackId: 'ai',
    order: 5,
    estimatedTime: '90 min',
    difficulty: 'Intermediaire',
    topics: ['Gemini', 'API Live', 'Multi-modal', 'SDK Gen AI'],
  },
  {
    id: 'ai-garden-forgotten',
    title: 'Requete du Jardin des Oublies',
    description: 'Un jeu aventure textuel pour apprendre ADK de Google. Creez un agent IA autonome capable de jouer au jeu a votre place.',
    codelabUrl: 'https://goo.gle/garden-forgotten-prompt',
    iconName: 'puzzle',
    trackId: 'ai',
    order: 6,
    estimatedTime: '75 min',
    difficulty: 'Intermediaire',
    topics: ['ADK', 'Agent autonome', 'Jeu textuel'],
  },
  {
    id: 'ai-gpu-kernels',
    title: 'Faire evoluer les noyaux GPU avec Gemini',
    description: 'Boucle agentique utilisant Gemini 2.5 Flash et Pro pour optimiser de maniere iterative les noyaux GPU AMD pour les performances.',
    codelabUrl: 'https://goo.gle/gpu-kernels-Gemini',
    iconName: 'lightbulb',
    trackId: 'ai',
    order: 7,
    estimatedTime: '60 min',
    difficulty: 'Avance',
    topics: ['GPU', 'Gemini Flash', 'Gemini Pro', 'Optimisation'],
  },
  {
    id: 'ai-agents-adk-mcp',
    title: 'Agents personnalises avec ADK MCP et Memory Bank',
    description: 'Concevez un systeme agentique complet avec la connectivite MCP orchestration ADK et memoire Memory Bank pour des agents IA professionnels.',
    codelabUrl: 'https://goo.gle/building-personalized-agents-adk-mcp',
    iconName: 'brain',
    trackId: 'ai',
    order: 8,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['ADK', 'MCP', 'Memory Bank', 'Agents personnalises'],
  },
  {
    id: 'ai-location-intelligence',
    title: 'Agent ADK Location Intelligence avec MCP',
    description: 'Creez un agent intelligence geographique avec ADK et Gemini 3.0 Pro. Utilisez des serveurs MCP distants pour BigQuery et Google Maps.',
    codelabUrl: 'https://goo.gle/build-location-intelligence-adk-mcp',
    iconName: 'globe',
    trackId: 'ai',
    order: 9,
    estimatedTime: '80 min',
    difficulty: 'Avance',
    topics: ['ADK', 'MCP', 'BigQuery', 'Google Maps'],
  },
  {
    id: 'ai-evaluate-agents',
    title: 'Evaluer des agents avec ADK',
    description: 'Evaluez les agents IA non deterministes avec le framework automatise ADK. Inspection visuelle tests unitaires et integration CI/CD.',
    codelabUrl: 'https://goo.gle/evaluating-agents-adk',
    iconName: 'clipboard-check',
    trackId: 'ai',
    order: 10,
    estimatedTime: '70 min',
    difficulty: 'Avance',
    topics: ['ADK', 'Tests', 'CI/CD', 'Evaluation'],
  },
  {
    id: 'ai-adk-bigquery-analytics',
    title: 'Analyse execution ADK avec BigQuery Agent Analytics',
    description: 'Creez un systeme multi-agents avec ADK et suivez activite via le plug-in BigQuery Agent Analytics. Examinez les traces de conversation.',
    codelabUrl: 'https://goo.gle/adk-agent-execution-big-query-agent-analytics-plugin',
    iconName: 'search',
    trackId: 'ai',
    order: 11,
    estimatedTime: '75 min',
    difficulty: 'Avance',
    topics: ['ADK', 'BigQuery', 'Multi-agents', 'Analytics'],
  },
  {
    id: 'ai-mcp-adk-a2a',
    title: 'Premiers pas avec MCP ADK et A2A',
    description: 'Creez un agent de devises qui effectue des conversions entre differentes devises avec le protocole MCP ADK et Agent2Agent A2A.',
    codelabUrl: 'https://goo.gle/getting-started-mcp-adk-a2a',
    iconName: 'link',
    trackId: 'ai',
    order: 12,
    estimatedTime: '70 min',
    difficulty: 'Intermediaire',
    topics: ['MCP', 'ADK', 'A2A', 'Agent de devises'],
  },
  {
    id: 'ai-agent-stack-action',
    title: 'La pile agents Google en action : ADK A2A et MCP',
    description: 'Creez un systeme multi-agents ecoute sociale avancee avec ADK A2A et MCP sur Google Cloud pour des experiences hyper personnalisees.',
    codelabUrl: 'https://goo.gle/agent-stack-in-action',
    iconName: 'workflow',
    trackId: 'ai',
    order: 13,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['ADK', 'A2A', 'MCP', 'Google Cloud', 'Multi-agents'],
  },
  {
    id: 'ai-adk-getting-started',
    title: 'Premiers pas avec Agent Development Kit (ADK)',
    description: 'Creez un agent unique capable utiliser un outil de recherche. Testez les agents dans interface navigateur ADK depuis un CLI et programmatiquement.',
    codelabUrl: 'https://goo.gle/agent-dev-kit',
    iconName: 'bot',
    trackId: 'ai',
    order: 14,
    estimatedTime: '60 min',
    difficulty: 'Debutant',
    topics: ['ADK', 'Agent unique', 'CLI', 'Recherche'],
  },
  {
    id: 'ai-multi-agent-adk',
    title: 'Creer des systemes multi-agents avec ADK',
    description: 'Decouvrez les systemes multi-agents avec Agent Development Kit. Apprenez a orchestrer plusieurs agents pour des taches complexes.',
    codelabUrl: 'https://goo.gle/mutli-agent-systems-adk',
    iconName: 'workflow',
    trackId: 'ai',
    order: 15,
    estimatedTime: '80 min',
    difficulty: 'Avance',
    topics: ['ADK', 'Multi-agents', 'Orchestration'],
  },
  {
    id: 'ai-vibecoding-gemini-cli',
    title: 'Agentverse - Vibecoding with Gemini CLI',
    description: 'Maitrisez avenir agentique sur Google Cloud avec une feuille de route de bout en bout pour un Agentverse puissant.',
    codelabUrl: 'https://goo.gle/vibecoding-gemini-cli',
    iconName: 'rocket',
    trackId: 'ai',
    order: 16,
    estimatedTime: '120 min',
    difficulty: 'Avance',
    topics: ['Gemini CLI', 'Agentverse', 'Google Cloud', 'DevOps'],
  },
  // ---- TRACK: Flutter (6 modules) ----
  {
    id: 'flutter-production-ai',
    title: 'Passer en production : app IA avec Flutter',
    description: 'Utilisez Flutter pour creer et valider rapidement des applications. Creez un prototype IA generative avec Vertex AI dans Firebase.',
    codelabUrl: 'https://goo.gle/flutter-youtube',
    iconName: 'rocket',
    trackId: 'flutter',
    order: 1,
    estimatedTime: '75 min',
    difficulty: 'Intermediaire',
    topics: ['Flutter', 'Vertex AI', 'Firebase', 'Production'],
  },
  {
    id: 'flutter-agent-builder',
    title: 'Agents IA avec Vertex AI Agent Builder et Flutter',
    description: 'Boostez votre workflow IA generative avec Vertex AI et Flutter. Exploitez les composants predefinis pour deployer des agents production.',
    codelabUrl: 'https://goo.gle/agent-builder-and-flutter',
    iconName: 'bot',
    trackId: 'flutter',
    order: 2,
    estimatedTime: '80 min',
    difficulty: 'Avance',
    topics: ['Vertex AI', 'Agent Builder', 'Flutter', 'IA generative'],
  },
  {
    id: 'flutter-ai-toolkit',
    title: 'AI Toolkit pour Flutter',
    description: 'Configurez et utilisez le kit outils Flutter AI pour ajouter des fenetres de chat IA en temps reel a vos applications avec differents LLM.',
    codelabUrl: 'https://goo.gle/ai-toolkit-flutter',
    iconName: 'sparkles',
    trackId: 'flutter',
    order: 3,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['Flutter AI Toolkit', 'Chat IA', 'LLM'],
  },
  {
    id: 'flutter-firebase-vertex',
    title: 'Firebase Vertex AI pour Flutter',
    description: 'Integrez IA generative a vos applications Flutter avec Firebase Vertex AI et API Gemini.',
    codelabUrl: 'https://goo.gle/firebase_vertexai_yt',
    iconName: 'flame',
    trackId: 'flutter',
    order: 4,
    estimatedTime: '45 min',
    difficulty: 'Debutant',
    topics: ['Firebase', 'Vertex AI', 'Gemini API', 'Flutter'],
  },
  {
    id: 'flutter-crossword-gemini',
    title: 'Mots croises multijoueurs avec Gemini et Flutter',
    description: 'Decouvrez comment les equipes Google ont cree un jeu de mots croises multijoueur avec Gemini Flutter et Firebase.',
    codelabUrl: 'https://goo.gle/solution-crossword',
    iconName: 'puzzle',
    trackId: 'flutter',
    order: 5,
    estimatedTime: '70 min',
    difficulty: 'Avance',
    topics: ['Gemini', 'Flutter', 'Firebase', 'Multijoueur'],
  },
  {
    id: 'flutter-vertex-codelab',
    title: 'Atelier Flutter + Vertex AI',
    description: 'Une application Flutter interactive qui exploite directement la puissance de API Gemini dans votre application Flutter.',
    codelabUrl: 'https://goo.gle/gemini-flutter-app',
    iconName: 'smartphone',
    trackId: 'flutter',
    order: 6,
    estimatedTime: '65 min',
    difficulty: 'Intermediaire',
    topics: ['Flutter', 'Vertex AI', 'Gemini', 'Application interactive'],
  },
  // ---- TRACK: Web (5 modules) ----
  {
    id: 'web-client-ai-reviews',
    title: 'Avis produits avec IA Web cote client',
    description: 'Exploitez IA sur appareil dans les applications Web pour ameliorer la qualite des avis produits : toxicite sentiment et notes generees.',
    codelabUrl: 'https://goo.gle/client-side-web-AI',
    iconName: 'sparkles',
    trackId: 'web',
    order: 1,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['IA cote client', 'Sentiment', 'Toxicite', 'Web'],
  },
  {
    id: 'web-client-translation',
    title: 'Traduction cote client avec IA',
    description: 'Exploitez IA sur appareil pour une traduction fluide et respectueuse de la confidentialite dans les fonctionnalites Web comme le chat.',
    codelabUrl: 'https://goo.gle/client-slide-translation',
    iconName: 'globe',
    trackId: 'web',
    order: 2,
    estimatedTime: '50 min',
    difficulty: 'Intermediaire',
    topics: ['Traduction', 'IA on-device', 'Confidentialite', 'Chat'],
  },
  {
    id: 'web-gemini-chrome-extension',
    title: 'API Gemini dans une extension Chrome',
    description: 'Utilisez API Gemini Cloud dans une extension Chrome pour etendre les capacites de votre navigateur.',
    codelabUrl: 'https://goo.gle/chrome-extensions-samples-tree',
    iconName: 'code',
    trackId: 'web',
    order: 3,
    estimatedTime: '55 min',
    difficulty: 'Intermediaire',
    topics: ['Chrome Extension', 'API Gemini', 'Cloud'],
  },
  {
    id: 'web-gemini-nano-chat',
    title: 'IA sur appareil avec Gemini Nano',
    description: 'Creez une extension Chrome avec une interface de chat utilisant API Prompt et le modele Gemini Nano integre a Chrome.',
    codelabUrl: 'https://goo.gle/3Q4xmgM',
    iconName: 'bot',
    trackId: 'web',
    order: 4,
    estimatedTime: '50 min',
    difficulty: 'Avance',
    topics: ['Gemini Nano', 'Chrome', 'Chat IA', 'On-device'],
  },
  {
    id: 'web-gemini-nano-summarization',
    title: 'Synthese sur appareil avec Gemini Nano',
    description: 'Creez une extension Chrome qui resume le contenu de onglet actif avec la bibliotheque lisibilite Mozilla et API de resume Chrome.',
    codelabUrl: 'https://goo.gle/ai-gemini-on-device-summarization',
    iconName: 'search',
    trackId: 'web',
    order: 5,
    estimatedTime: '55 min',
    difficulty: 'Avance',
    topics: ['Gemini Nano', 'Resume', 'Chrome Extension', 'On-device'],
  },
  // ---- TRACK: Cloud (7 modules) ----
  {
    id: 'cloud-youtube-summarizer',
    title: 'Synthese YouTube avec Gemini',
    description: 'Creez une application Web qui resume les videos YouTube avec API Gemini et SDK Google Gen AI.',
    codelabUrl: 'https://goo.gle/gemini-youtube-summarizer',
    iconName: 'sparkles',
    trackId: 'cloud',
    order: 1,
    estimatedTime: '60 min',
    difficulty: 'Debutant',
    topics: ['API Gemini', 'SDK Gen AI', 'YouTube', 'Resume'],
  },
  {
    id: 'cloud-agentic-ai',
    title: 'IA agentique avec Google Cloud',
    description: 'Creez des agents individuels avec des outils interaction base de donnees et recherche Internet via API Gemini puis orchestrez avec LangGraph.',
    codelabUrl: 'https://goo.gle/Multi-Agent-Systems',
    iconName: 'workflow',
    trackId: 'cloud',
    order: 2,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['LangGraph', 'Multi-agents', 'API Gemini', 'Orchestration'],
  },
  {
    id: 'cloud-gemini-langchain4j',
    title: 'Gemini avec Vertex AI et LangChain4j',
    description: 'Creez des applications avec Gemini en Java ou Python. Streaming chatbot entrees multi-modales RAG et utilisation de Gemma avec Ollama.',
    codelabUrl: 'https://goo.gle/gemini-in-java',
    iconName: 'code',
    trackId: 'cloud',
    order: 3,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['Vertex AI', 'LangChain4j', 'RAG', 'Gemma', 'Java'],
  },
  {
    id: 'cloud-gemini-code-assist',
    title: 'Tests avec Gemini Code Assist',
    description: 'Utilisez Gemini Code Assist pour ameliorer la qualite une application Web Python : generer des tests identifier et corriger les erreurs.',
    codelabUrl: 'https://goo.gle/testing-with-gemini-code-assist',
    iconName: 'clipboard-check',
    trackId: 'cloud',
    order: 4,
    estimatedTime: '65 min',
    difficulty: 'Intermediaire',
    topics: ['Gemini Code Assist', 'Tests', 'Python', 'Cloud Shell'],
  },
  {
    id: 'cloud-code-assist-enterprise',
    title: 'Personnalisation avec Gemini Code Assist Enterprise',
    description: 'Exploitez la personnalisation du code de Gemini Code Assist Enterprise pour adapter les suggestions a vos conventions de codage.',
    codelabUrl: 'https://goo.gle/code-assist-enterprise',
    iconName: 'server',
    trackId: 'cloud',
    order: 5,
    estimatedTime: '70 min',
    difficulty: 'Avance',
    topics: ['Code Assist Enterprise', 'Personnalisation', 'Indexation'],
  },
  {
    id: 'cloud-aidemy-multi-agent',
    title: 'Aidemy : systemes multi-agents avec LangGraph',
    description: 'Apprenez a creer orchestrer et deployer des systemes multi-agents collaboratifs complexes avec LangGraph divers LLM et Google Cloud.',
    codelabUrl: 'https://goo.gle/Multi-Agent-Systems',
    iconName: 'brain',
    trackId: 'cloud',
    order: 6,
    estimatedTime: '90 min',
    difficulty: 'Avance',
    topics: ['LangGraph', 'Multi-agents', 'LLM', 'Google Cloud'],
  },
  {
    id: 'cloud-devops-ai',
    title: 'De Monolith a Magic : DevOps optimise par IA',
    description: 'Conteneurisez avec Docker deployez sur Cloud Run creez un pipeline CI/CD automatise utilisez Gemini pour refactoriser le code.',
    codelabUrl: 'https://goo.gle/app-mod-workshop',
    iconName: 'rocket',
    trackId: 'cloud',
    order: 7,
    estimatedTime: '120 min',
    difficulty: 'Avance',
    topics: ['Docker', 'Cloud Run', 'CI/CD', 'Gemini Vision'],
  },
  // ---- TRACK: Angular (3 modules) ----
  {
    id: 'angular-vertex-starter',
    title: 'Kit de demarrage Angular + Vertex AI',
    description: 'Tout ce dont vous avez besoin pour creer une application avec Vertex AI dans Firebase avec Angular.',
    codelabUrl: 'https://goo.gle/vertex-angular-starter-kit',
    iconName: 'hexagon',
    trackId: 'angular',
    order: 1,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['Angular', 'Vertex AI', 'Firebase'],
  },
  {
    id: 'angular-genkit-starter',
    title: 'Kit de demarrage Angular + Genkit',
    description: 'Tout ce dont vous avez besoin pour creer une application avec Genkit avec Angular.',
    codelabUrl: 'https://goo.gle/genkit-angular-starter-kit',
    iconName: 'flame',
    trackId: 'angular',
    order: 2,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['Angular', 'Genkit', 'IA generative'],
  },
  {
    id: 'angular-genkit-story',
    title: 'Createur de stories Angular + Genkit',
    description: 'Utilisez Angular et Genkit pour creer une bande dessinee interactive choisissez votre propre aventure.',
    codelabUrl: 'https://goo.gle/genkit-angular-story-generator',
    iconName: 'palette',
    trackId: 'angular',
    order: 3,
    estimatedTime: '70 min',
    difficulty: 'Avance',
    topics: ['Angular', 'Genkit', 'Story Generator', 'Interactif'],
  },
  // ---- TRACK: Kotlin (5 modules) ----
  {
    id: 'kotlin-litert-android',
    title: 'LiteRT pour Android',
    description: 'LiteRT pour Android fournit des environnements execution predefinis et personnalisables pour executer des modeles TensorFlow PyTorch et JAX.',
    codelabUrl: 'https://goo.gle/edge-litert-android',
    iconName: 'smartphone',
    trackId: 'kotlin',
    order: 1,
    estimatedTime: '65 min',
    difficulty: 'Intermediaire',
    topics: ['LiteRT', 'TensorFlow', 'PyTorch', 'Android'],
  },
  {
    id: 'kotlin-mlkit-genai',
    title: 'API ML Kit GenAI',
    description: 'API IA generative de ML Kit qui utilisent Gemini Nano pour effectuer des taches grace au traitement sur appareil via AICore.',
    codelabUrl: 'https://goo.gle/ml-kit-genai-apis',
    iconName: 'sparkles',
    trackId: 'kotlin',
    order: 2,
    estimatedTime: '50 min',
    difficulty: 'Intermediaire',
    topics: ['ML Kit', 'Gemini Nano', 'AICore', 'On-device'],
  },
  {
    id: 'kotlin-android-ai',
    title: 'Documentation Android AI',
    description: 'Creez des experiences intelligentes sur Android avec IA. Guide complet pour integrer intelligence artificielle dans vos applications Android.',
    codelabUrl: 'https://goo.gle/devfest24-ai-on-android',
    iconName: 'brain',
    trackId: 'kotlin',
    order: 3,
    estimatedTime: '55 min',
    difficulty: 'Debutant',
    topics: ['Android', 'IA', 'Experiences intelligentes'],
  },
  {
    id: 'kotlin-firebase-ai-logic',
    title: 'Logique IA Firebase',
    description: 'Creez des applications mobiles et Web optimisees par IA avec les modeles Gemini et Imagen via Firebase AI Logic.',
    codelabUrl: 'https://goo.gle/devfest24-gemini-api-vertex',
    iconName: 'flame',
    trackId: 'kotlin',
    order: 4,
    estimatedTime: '60 min',
    difficulty: 'Intermediaire',
    topics: ['Firebase AI Logic', 'Gemini', 'Imagen'],
  },
  {
    id: 'kotlin-llm-inference',
    title: 'IA generative integree avec LLM Inference',
    description: 'Executez des grands modeles de langage (LLM) entierement sur appareil Android pour generer du texte recuperer des informations et resumer des documents.',
    codelabUrl: 'https://goo.gle/devfest24-llm-inference-android',
    iconName: 'code',
    trackId: 'kotlin',
    order: 5,
    estimatedTime: '60 min',
    difficulty: 'Avance',
    topics: ['LLM Inference', 'On-device', 'Generation de texte'],
  },
  // ---- TRACK: Google Skills (5 modules) ----
  {
    id: 'skills-labs-build-ai',
    title: 'Labs for Build w/AI',
    description: 'Labs qui clonent le depot gen-ai-github demontrant comment utiliser Gemini et Vertex AI pour le developpement applications IA.',
    codelabUrl: 'https://www.skills.google/program_groups/gdg-on-campus-universit-catholique-de-bukavu-bukavu-democratic-republic-of-the-congo-ai-builder-kickoff-from-idea-to-prototype/paths/441',
    iconName: 'rocket',
    trackId: 'skills',
    order: 1,
    estimatedTime: '90 min',
    difficulty: 'Debutant',
    topics: ['Gemini', 'Vertex AI', 'Labs', 'Build with AI'],
  },
  {
    id: 'skills-gemini-learning',
    title: 'New Gemini Learning Paths',
    description: 'Analysez et raisonnez sur des donnees multimodales avec Gemini. Ameliorez les capacites du modele Gemini avec des techniques avancees.',
    codelabUrl: 'https://www.skills.google/program_groups/gdg-on-campus-universit-catholique-de-bukavu-bukavu-democratic-republic-of-the-congo-ai-builder-kickoff-from-idea-to-prototype/paths/2184',
    iconName: 'sparkles',
    trackId: 'skills',
    order: 2,
    estimatedTime: '120 min',
    difficulty: 'Intermediaire',
    topics: ['Gemini', 'Multimodal', 'Learning Path'],
  },
  {
    id: 'skills-agents-adk',
    title: 'Develop Intelligent Agents with ADK',
    description: 'Contenu Skillsboost qui accompagne les ateliers pratiques ADK. Apprenez a developper des agents intelligents avec Agent Development Kit.',
    codelabUrl: 'https://www.skills.google/program_groups/gdg-on-campus-universit-catholique-de-bukavu-bukavu-democratic-republic-of-the-congo-ai-builder-kickoff-from-idea-to-prototype/paths/2658',
    iconName: 'bot',
    trackId: 'skills',
    order: 3,
    estimatedTime: '90 min',
    difficulty: 'Intermediaire',
    topics: ['ADK', 'Agents intelligents', 'Skillsboost'],
  },
  {
    id: 'skills-genai-developers',
    title: 'Advanced: Generative AI for Developers',
    description: 'Parcours apprentissage IA generative avec un focus technique pour les developpeurs applications ingenieurs ML et Data Scientists.',
    codelabUrl: 'https://www.skills.google/program_groups/gdg-on-campus-universit-catholique-de-bukavu-bukavu-democratic-republic-of-the-congo-ai-builder-kickoff-from-idea-to-prototype/paths/183',
    iconName: 'brain',
    trackId: 'skills',
    order: 4,
    estimatedTime: '180 min',
    difficulty: 'Avance',
    topics: ['IA generative', 'ML Engineering', 'Data Science'],
  },
  {
    id: 'skills-ml-engineer',
    title: 'Machine Learning Engineer',
    description: 'Un ingenieur Machine Learning concoit construit met en production optimise opere et maintient des systemes ML. Parcours complet de certification.',
    codelabUrl: 'https://www.skills.google/program_groups/gdg-on-campus-universit-catholique-de-bukavu-bukavu-democratic-republic-of-the-congo-ai-builder-kickoff-from-idea-to-prototype/paths/17',
    iconName: 'lightbulb',
    trackId: 'skills',
    order: 5,
    estimatedTime: '240 min',
    difficulty: 'Avance',
    topics: ['Machine Learning', 'MLOps', 'Production ML'],
  },
];

// ============================================
// HELPERS
// ============================================
export function getTrackById(trackId) {
  return TRACKS.find(function(t) { return t.id === trackId; });
}

export function getModulesByTrack(trackId) {
  return MODULES.filter(function(m) { return m.trackId === trackId; }).sort(function(a, b) { return a.order - b.order; });
}

export function getTrackProgress(trackId, progressMap) {
  var trackModules = getModulesByTrack(trackId);
  var completed = trackModules.filter(function(m) { return progressMap[m.id] && progressMap[m.id].examScore >= 6; }).length;
  return {
    total: trackModules.length,
    completed: completed,
    percentage: trackModules.length > 0 ? (completed / trackModules.length) * 100 : 0,
  };
}

export const DIFFICULTY_COLORS = {
  'Debutant': 'text-accent-400 bg-accent-500/10 border-accent-500/30',
  'Intermediaire': 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  'Avance': 'text-red-400 bg-red-500/10 border-red-500/30',
  Beginner: 'text-accent-400 bg-accent-500/10 border-accent-500/30',
  Intermediate: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  Advanced: 'text-red-400 bg-red-500/10 border-red-500/30',
};

export const EXAM_CONFIG = {
  MCQ_COUNT: 7,
  OPEN_COUNT: 3,
  MCQ_TIME_SECONDS: 30,
  OPEN_TIME_SECONDS: 120,
  MAX_ATTEMPTS: 2,
  PASSING_SCORE: 6,
  MAX_SCORE: 10,
  POINTS_PER_SECTION: 10,
};

export const BADGE_MESSAGES = {
  completed: 'Felicitations ! Vous avez obtenu votre badge de certification.',
  failed: 'Continuez a apprendre. Revoyez le codelab et preparez-vous pour reessayer.',
  locked: 'Cet examen a ete verrouille en raison de violations de la politique.',
  pending: 'Votre soumission est en cours examen.',
};
