// Codelab modules for Build with AI season
// Icons are Lucide icon names — mapped in components
export const MODULES = [
  {
    id: 'intro-ai-fundamentals',
    title: 'Introduction to AI Fundamentals',
    description: 'Learn the basics of Artificial Intelligence, machine learning concepts, and how AI is transforming software development.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-fundamentals',
    iconName: 'brain',
    order: 1,
    estimatedTime: '45 min',
    difficulty: 'Beginner',
    topics: ['AI Basics', 'Machine Learning', 'Neural Networks'],
  },
  {
    id: 'gemini-api-basics',
    title: 'Getting Started with Gemini API',
    description: 'Set up and use the Gemini API for text generation, multi-modal inputs, and building your first AI-powered application.',
    codelabUrl: 'https://codelabs.developers.google.com/gemini-api',
    iconName: 'sparkles',
    order: 2,
    estimatedTime: '60 min',
    difficulty: 'Beginner',
    topics: ['Gemini API', 'Text Generation', 'Multi-modal AI'],
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering Mastery',
    description: 'Master prompt engineering techniques including few-shot learning, chain-of-thought, and structured output generation.',
    codelabUrl: 'https://codelabs.developers.google.com/prompt-engineering',
    iconName: 'lightbulb',
    order: 3,
    estimatedTime: '50 min',
    difficulty: 'Intermediate',
    topics: ['Prompt Design', 'Few-shot Learning', 'Chain-of-Thought'],
  },
  {
    id: 'vertex-ai-studio',
    title: 'Building with Vertex AI Studio',
    description: 'Explore Vertex AI Studio for model tuning, deployment, and creating production-ready AI pipelines.',
    codelabUrl: 'https://codelabs.developers.google.com/vertex-ai-studio',
    iconName: 'rocket',
    order: 4,
    estimatedTime: '75 min',
    difficulty: 'Intermediate',
    topics: ['Vertex AI', 'Model Tuning', 'AI Pipelines'],
  },
  {
    id: 'ai-agents-adk',
    title: 'AI Agent Development with ADK',
    description: 'Build autonomous AI agents using the Agent Development Kit, including tool use, memory, and multi-step reasoning.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-agents-adk',
    iconName: 'bot',
    order: 5,
    estimatedTime: '90 min',
    difficulty: 'Advanced',
    topics: ['AI Agents', 'ADK', 'Tool Use', 'Reasoning'],
  },
  {
    id: 'mcp-context-protocol',
    title: 'Model Context Protocol (MCP)',
    description: 'Implement the Model Context Protocol for managing context windows, memory persistence, and stateful conversations.',
    codelabUrl: 'https://codelabs.developers.google.com/mcp',
    iconName: 'puzzle',
    order: 6,
    estimatedTime: '80 min',
    difficulty: 'Advanced',
    topics: ['MCP', 'Context Management', 'Memory'],
  },
  {
    id: 'a2a-communication',
    title: 'Agent-to-Agent (A2A) Communication',
    description: 'Design multi-agent systems with A2A protocols, enabling agents to collaborate, delegate, and coordinate tasks.',
    codelabUrl: 'https://codelabs.developers.google.com/a2a',
    iconName: 'link',
    order: 7,
    estimatedTime: '85 min',
    difficulty: 'Advanced',
    topics: ['A2A Protocol', 'Multi-Agent Systems', 'Coordination'],
  },
  {
    id: 'responsible-ai',
    title: 'Responsible AI & Safety',
    description: 'Apply responsible AI principles including safety filters, bias detection, fairness metrics, and ethical deployment strategies.',
    codelabUrl: 'https://codelabs.developers.google.com/responsible-ai',
    iconName: 'shield-check',
    order: 8,
    estimatedTime: '55 min',
    difficulty: 'Intermediate',
    topics: ['AI Safety', 'Bias Detection', 'Ethics'],
  },
  {
    id: 'genai-flutter',
    title: 'Generative AI with Flutter',
    description: 'Integrate generative AI capabilities into Flutter mobile applications using the Gemini API and Firebase ML Kit.',
    codelabUrl: 'https://codelabs.developers.google.com/genai-flutter',
    iconName: 'smartphone',
    order: 9,
    estimatedTime: '70 min',
    difficulty: 'Intermediate',
    topics: ['Flutter', 'Gemini Mobile', 'Firebase ML'],
  },
  {
    id: 'cloud-functions-ai',
    title: 'Cloud Functions with AI',
    description: 'Build serverless AI-powered APIs using Cloud Functions, integrating Gemini models for real-time inference.',
    codelabUrl: 'https://codelabs.developers.google.com/cloud-functions-ai',
    iconName: 'cloud',
    order: 10,
    estimatedTime: '65 min',
    difficulty: 'Intermediate',
    topics: ['Cloud Functions', 'Serverless AI', 'API Design'],
  },
  {
    id: 'langchain-gemini',
    title: 'LangChain with Gemini',
    description: 'Build complex AI chains and retrieval-augmented generation pipelines using LangChain with Gemini as the LLM backend.',
    codelabUrl: 'https://codelabs.developers.google.com/langchain-gemini',
    iconName: 'git-branch',
    order: 11,
    estimatedTime: '90 min',
    difficulty: 'Advanced',
    topics: ['LangChain', 'RAG', 'Vector Stores'],
  },
  {
    id: 'ai-image-generation',
    title: 'AI Image Generation & Vision',
    description: 'Use Imagen and Gemini Vision APIs for image generation, analysis, and building visual AI applications.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-image-gen',
    iconName: 'image',
    order: 12,
    estimatedTime: '60 min',
    difficulty: 'Intermediate',
    topics: ['Imagen', 'Vision API', 'Multi-modal'],
  },
  {
    id: 'ai-testing-evaluation',
    title: 'AI Model Testing & Evaluation',
    description: 'Learn systematic approaches to evaluate, benchmark, and test AI models for accuracy, safety, and performance.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-eval',
    iconName: 'clipboard-check',
    order: 13,
    estimatedTime: '55 min',
    difficulty: 'Intermediate',
    topics: ['Benchmarking', 'Evaluation Metrics', 'Testing'],
  },
  {
    id: 'grounding-search',
    title: 'Grounding with Google Search',
    description: 'Implement grounding techniques using Google Search to reduce hallucination and improve factual accuracy in AI responses.',
    codelabUrl: 'https://codelabs.developers.google.com/grounding-search',
    iconName: 'search',
    order: 14,
    estimatedTime: '50 min',
    difficulty: 'Intermediate',
    topics: ['Grounding', 'Search API', 'Factual AI'],
  },
  {
    id: 'ai-orchestration',
    title: 'AI Workflow Orchestration',
    description: 'Design and implement complex AI workflows with task orchestration, parallel execution, and error handling patterns.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-orchestration',
    iconName: 'workflow',
    order: 15,
    estimatedTime: '85 min',
    difficulty: 'Advanced',
    topics: ['Orchestration', 'Workflows', 'Parallel Execution'],
  },
  {
    id: 'production-deployment',
    title: 'Production AI Deployment',
    description: 'Deploy AI applications to production with monitoring, scaling, CI/CD pipelines, and operational best practices.',
    codelabUrl: 'https://codelabs.developers.google.com/ai-deployment',
    iconName: 'server',
    order: 16,
    estimatedTime: '75 min',
    difficulty: 'Advanced',
    topics: ['Deployment', 'Monitoring', 'CI/CD', 'Scaling'],
  },
];

export const DIFFICULTY_COLORS = {
  Beginner: 'text-accent-400 bg-accent-500/10 border-accent-500/30',
  Intermediate: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  Advanced: 'text-red-400 bg-red-500/10 border-red-500/30',
};

export const EXAM_CONFIG = {
  MCQ_COUNT: 7,
  OPEN_COUNT: 3,
  MCQ_TIME_SECONDS: 30,
  OPEN_TIME_SECONDS: 300,
  MAX_ATTEMPTS: 2,
  PASSING_SCORE: 6,
  MAX_SCORE: 10,
  POINTS_PER_SECTION: 10,
};

export const BADGE_MESSAGES = {
  completed: 'Congratulations! You have earned your certification badge.',
  failed: 'Keep learning. Review the codelab and prepare to try again.',
  locked: 'This exam has been locked due to policy violations.',
  pending: 'Your submission is being reviewed.',
};
